# Generated by Django 4.1.6 on 2023-04-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='journeys',
            fields=[
                ('journey_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_location', models.CharField(default='', max_length=200)),
                ('entry_time', models.DateTimeField(verbose_name='')),
                ('exit_location', models.CharField(default='', max_length=200)),
                ('exit_time', models.DateTimeField(verbose_name='')),
                ('fare', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
