# Generated by Django 4.1.6 on 2023-04-14 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='journeys',
            new_name='journey',
        ),
    ]
