# Generated by Django 4.1.6 on 2023-04-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_passenger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
    ]
