# Generated by Django 4.1.6 on 2023-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
