# Generated by Django 4.1.6 on 2023-04-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_passenger_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='aadhar',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_visited_station',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
    ]
