# Generated by Django 4.1.6 on 2023-04-16 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0009_pad'),
    ]

    operations = [
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
                ('sex', models.CharField(default='Male', max_length=20)),
                ('status', models.CharField(default='NOT Travelling', max_length=20)),
                ('balance', models.IntegerField(blank=True, default=1, null=True)),
                ('password', models.CharField(default='**', max_length=20)),
                ('age', models.IntegerField(blank=True, default=1, null=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('aadhar', models.CharField(default='', max_length=20)),
                ('place', models.CharField(default='', max_length=20)),
                ('last_visited_station', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='pad',
        ),
    ]
