# Generated by Django 4.1.6 on 2023-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_delete_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='entry_time',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='journey',
            name='exit_time',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
    ]
