# Generated by Django 4.1.6 on 2023-04-18 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_journey_entry_time_alter_journey_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journey',
            name='exit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
