# Generated by Django 4.1.6 on 2023-04-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passengers',
        ),
    ]
